// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package msa_monitor

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MonitorClient is the client API for Monitor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MonitorClient interface {
	AddService(ctx context.Context, in *RequestAddService, opts ...grpc.CallOption) (*Response, error)
	DeleteService(ctx context.Context, in *RequestDelService, opts ...grpc.CallOption) (*Response, error)
	RebuildService(ctx context.Context, in *RequestRebuildService, opts ...grpc.CallOption) (*Response, error)
	SetService(ctx context.Context, in *RequestSetService, opts ...grpc.CallOption) (*Response, error)
}

type monitorClient struct {
	cc grpc.ClientConnInterface
}

func NewMonitorClient(cc grpc.ClientConnInterface) MonitorClient {
	return &monitorClient{cc}
}

func (c *monitorClient) AddService(ctx context.Context, in *RequestAddService, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/msa_monitor.Monitor/AddService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorClient) DeleteService(ctx context.Context, in *RequestDelService, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/msa_monitor.Monitor/DeleteService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorClient) RebuildService(ctx context.Context, in *RequestRebuildService, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/msa_monitor.Monitor/RebuildService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorClient) SetService(ctx context.Context, in *RequestSetService, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/msa_monitor.Monitor/SetService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MonitorServer is the server API for Monitor service.
// All implementations must embed UnimplementedMonitorServer
// for forward compatibility
type MonitorServer interface {
	AddService(context.Context, *RequestAddService) (*Response, error)
	DeleteService(context.Context, *RequestDelService) (*Response, error)
	RebuildService(context.Context, *RequestRebuildService) (*Response, error)
	SetService(context.Context, *RequestSetService) (*Response, error)
	mustEmbedUnimplementedMonitorServer()
}

// UnimplementedMonitorServer must be embedded to have forward compatible implementations.
type UnimplementedMonitorServer struct {
}

func (UnimplementedMonitorServer) AddService(context.Context, *RequestAddService) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddService not implemented")
}
func (UnimplementedMonitorServer) DeleteService(context.Context, *RequestDelService) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteService not implemented")
}
func (UnimplementedMonitorServer) RebuildService(context.Context, *RequestRebuildService) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RebuildService not implemented")
}
func (UnimplementedMonitorServer) SetService(context.Context, *RequestSetService) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetService not implemented")
}
func (UnimplementedMonitorServer) mustEmbedUnimplementedMonitorServer() {}

// UnsafeMonitorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MonitorServer will
// result in compilation errors.
type UnsafeMonitorServer interface {
	mustEmbedUnimplementedMonitorServer()
}

func RegisterMonitorServer(s grpc.ServiceRegistrar, srv MonitorServer) {
	s.RegisterService(&Monitor_ServiceDesc, srv)
}

func _Monitor_AddService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestAddService)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorServer).AddService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/msa_monitor.Monitor/AddService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorServer).AddService(ctx, req.(*RequestAddService))
	}
	return interceptor(ctx, in, info, handler)
}

func _Monitor_DeleteService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestDelService)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorServer).DeleteService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/msa_monitor.Monitor/DeleteService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorServer).DeleteService(ctx, req.(*RequestDelService))
	}
	return interceptor(ctx, in, info, handler)
}

func _Monitor_RebuildService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestRebuildService)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorServer).RebuildService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/msa_monitor.Monitor/RebuildService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorServer).RebuildService(ctx, req.(*RequestRebuildService))
	}
	return interceptor(ctx, in, info, handler)
}

func _Monitor_SetService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestSetService)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorServer).SetService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/msa_monitor.Monitor/SetService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorServer).SetService(ctx, req.(*RequestSetService))
	}
	return interceptor(ctx, in, info, handler)
}

// Monitor_ServiceDesc is the grpc.ServiceDesc for Monitor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Monitor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "msa_monitor.Monitor",
	HandlerType: (*MonitorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddService",
			Handler:    _Monitor_AddService_Handler,
		},
		{
			MethodName: "DeleteService",
			Handler:    _Monitor_DeleteService_Handler,
		},
		{
			MethodName: "RebuildService",
			Handler:    _Monitor_RebuildService_Handler,
		},
		{
			MethodName: "SetService",
			Handler:    _Monitor_SetService_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "msa/proto/msa_monitor.proto",
}
