// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: proto/msa_monitor.proto

package msa_monitor

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	msa_utils "x-msa-core/grpc/msa_utils"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestAddService struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Repo      string `protobuf:"bytes,1,opt,name=Repo,proto3" json:"Repo,omitempty"`
	GroupType string `protobuf:"bytes,2,opt,name=GroupType,proto3" json:"GroupType,omitempty"`
	Key       string `protobuf:"bytes,3,opt,name=Key,proto3" json:"Key,omitempty"`
}

func (x *RequestAddService) Reset() {
	*x = RequestAddService{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_msa_monitor_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestAddService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestAddService) ProtoMessage() {}

func (x *RequestAddService) ProtoReflect() protoreflect.Message {
	mi := &file_proto_msa_monitor_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestAddService.ProtoReflect.Descriptor instead.
func (*RequestAddService) Descriptor() ([]byte, []int) {
	return file_proto_msa_monitor_proto_rawDescGZIP(), []int{0}
}

func (x *RequestAddService) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *RequestAddService) GetGroupType() string {
	if x != nil {
		return x.GroupType
	}
	return ""
}

func (x *RequestAddService) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type RequestDelService struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupType string `protobuf:"bytes,1,opt,name=GroupType,proto3" json:"GroupType,omitempty"`
	Key       string `protobuf:"bytes,2,opt,name=Key,proto3" json:"Key,omitempty"`
}

func (x *RequestDelService) Reset() {
	*x = RequestDelService{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_msa_monitor_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestDelService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestDelService) ProtoMessage() {}

func (x *RequestDelService) ProtoReflect() protoreflect.Message {
	mi := &file_proto_msa_monitor_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestDelService.ProtoReflect.Descriptor instead.
func (*RequestDelService) Descriptor() ([]byte, []int) {
	return file_proto_msa_monitor_proto_rawDescGZIP(), []int{1}
}

func (x *RequestDelService) GetGroupType() string {
	if x != nil {
		return x.GroupType
	}
	return ""
}

func (x *RequestDelService) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type RequestRebuildService struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupType string `protobuf:"bytes,1,opt,name=GroupType,proto3" json:"GroupType,omitempty"`
	Key       string `protobuf:"bytes,2,opt,name=Key,proto3" json:"Key,omitempty"`
}

func (x *RequestRebuildService) Reset() {
	*x = RequestRebuildService{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_msa_monitor_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestRebuildService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestRebuildService) ProtoMessage() {}

func (x *RequestRebuildService) ProtoReflect() protoreflect.Message {
	mi := &file_proto_msa_monitor_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestRebuildService.ProtoReflect.Descriptor instead.
func (*RequestRebuildService) Descriptor() ([]byte, []int) {
	return file_proto_msa_monitor_proto_rawDescGZIP(), []int{2}
}

func (x *RequestRebuildService) GetGroupType() string {
	if x != nil {
		return x.GroupType
	}
	return ""
}

func (x *RequestRebuildService) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type RequestSetService struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupType string             `protobuf:"bytes,1,opt,name=GroupType,proto3" json:"GroupType,omitempty"`
	Key       string             `protobuf:"bytes,2,opt,name=Key,proto3" json:"Key,omitempty"`
	Command   msa_utils.Commands `protobuf:"varint,3,opt,name=Command,proto3,enum=msa_utils.Commands" json:"Command,omitempty"`
}

func (x *RequestSetService) Reset() {
	*x = RequestSetService{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_msa_monitor_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestSetService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestSetService) ProtoMessage() {}

func (x *RequestSetService) ProtoReflect() protoreflect.Message {
	mi := &file_proto_msa_monitor_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestSetService.ProtoReflect.Descriptor instead.
func (*RequestSetService) Descriptor() ([]byte, []int) {
	return file_proto_msa_monitor_proto_rawDescGZIP(), []int{3}
}

func (x *RequestSetService) GetGroupType() string {
	if x != nil {
		return x.GroupType
	}
	return ""
}

func (x *RequestSetService) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *RequestSetService) GetCommand() msa_utils.Commands {
	if x != nil {
		return x.Command
	}
	return msa_utils.Commands(0)
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_msa_monitor_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_msa_monitor_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_proto_msa_monitor_proto_rawDescGZIP(), []int{4}
}

func (x *Response) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_msa_monitor_proto protoreflect.FileDescriptor

var file_proto_msa_monitor_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x73, 0x61, 0x5f, 0x6d, 0x6f, 0x6e, 0x69,
	0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x6d, 0x73, 0x61, 0x5f, 0x6d,
	0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x1a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x73,
	0x61, 0x5f, 0x75, 0x74, 0x69, 0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x57, 0x0a,
	0x11, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x41, 0x64, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x52, 0x65, 0x70, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x52, 0x65, 0x70, 0x6f, 0x12, 0x1c, 0x0a, 0x09, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x54,
	0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x4b, 0x65, 0x79, 0x22, 0x43, 0x0a, 0x11, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x44, 0x65, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x54, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4b, 0x65, 0x79, 0x22, 0x47, 0x0a, 0x15, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x54, 0x79, 0x70,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x4b, 0x65, 0x79, 0x22, 0x72, 0x0a, 0x11, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x53,
	0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x54, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4b, 0x65, 0x79, 0x12, 0x2d, 0x0a, 0x07, 0x43, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x6d, 0x73, 0x61,
	0x5f, 0x75, 0x74, 0x69, 0x6c, 0x73, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x52,
	0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x22, 0x24, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x32, 0xa8,
	0x02, 0x0a, 0x07, 0x4d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x12, 0x43, 0x0a, 0x0a, 0x41, 0x64,
	0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x1e, 0x2e, 0x6d, 0x73, 0x61, 0x5f, 0x6d,
	0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x41, 0x64,
	0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x1a, 0x15, 0x2e, 0x6d, 0x73, 0x61, 0x5f, 0x6d,
	0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x46, 0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x1e, 0x2e, 0x6d, 0x73, 0x61, 0x5f, 0x6d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x2e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x44, 0x65, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x1a, 0x15, 0x2e, 0x6d, 0x73, 0x61, 0x5f, 0x6d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x2e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4b, 0x0a, 0x0e, 0x52, 0x65, 0x62, 0x75, 0x69,
	0x6c, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x22, 0x2e, 0x6d, 0x73, 0x61, 0x5f,
	0x6d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52,
	0x65, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x1a, 0x15, 0x2e,
	0x6d, 0x73, 0x61, 0x5f, 0x6d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x2e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x43, 0x0a, 0x0a, 0x53, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x1e, 0x2e, 0x6d, 0x73, 0x61, 0x5f, 0x6d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72,
	0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x53, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x1a, 0x15, 0x2e, 0x6d, 0x73, 0x61, 0x5f, 0x6d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72,
	0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x12, 0x5a, 0x10, 0x67, 0x72, 0x70,
	0x63, 0x2f, 0x6d, 0x73, 0x61, 0x5f, 0x6d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_msa_monitor_proto_rawDescOnce sync.Once
	file_proto_msa_monitor_proto_rawDescData = file_proto_msa_monitor_proto_rawDesc
)

func file_proto_msa_monitor_proto_rawDescGZIP() []byte {
	file_proto_msa_monitor_proto_rawDescOnce.Do(func() {
		file_proto_msa_monitor_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_msa_monitor_proto_rawDescData)
	})
	return file_proto_msa_monitor_proto_rawDescData
}

var file_proto_msa_monitor_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_msa_monitor_proto_goTypes = []interface{}{
	(*RequestAddService)(nil),     // 0: msa_monitor.RequestAddService
	(*RequestDelService)(nil),     // 1: msa_monitor.RequestDelService
	(*RequestRebuildService)(nil), // 2: msa_monitor.RequestRebuildService
	(*RequestSetService)(nil),     // 3: msa_monitor.RequestSetService
	(*Response)(nil),              // 4: msa_monitor.Response
	(msa_utils.Commands)(0),       // 5: msa_utils.Commands
}
var file_proto_msa_monitor_proto_depIdxs = []int32{
	5, // 0: msa_monitor.RequestSetService.Command:type_name -> msa_utils.Commands
	0, // 1: msa_monitor.Monitor.AddService:input_type -> msa_monitor.RequestAddService
	1, // 2: msa_monitor.Monitor.DeleteService:input_type -> msa_monitor.RequestDelService
	2, // 3: msa_monitor.Monitor.RebuildService:input_type -> msa_monitor.RequestRebuildService
	3, // 4: msa_monitor.Monitor.SetService:input_type -> msa_monitor.RequestSetService
	4, // 5: msa_monitor.Monitor.AddService:output_type -> msa_monitor.Response
	4, // 6: msa_monitor.Monitor.DeleteService:output_type -> msa_monitor.Response
	4, // 7: msa_monitor.Monitor.RebuildService:output_type -> msa_monitor.Response
	4, // 8: msa_monitor.Monitor.SetService:output_type -> msa_monitor.Response
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_msa_monitor_proto_init() }
func file_proto_msa_monitor_proto_init() {
	if File_proto_msa_monitor_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_msa_monitor_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestAddService); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_msa_monitor_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestDelService); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_msa_monitor_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestRebuildService); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_msa_monitor_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestSetService); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_msa_monitor_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_msa_monitor_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_msa_monitor_proto_goTypes,
		DependencyIndexes: file_proto_msa_monitor_proto_depIdxs,
		MessageInfos:      file_proto_msa_monitor_proto_msgTypes,
	}.Build()
	File_proto_msa_monitor_proto = out.File
	file_proto_msa_monitor_proto_rawDesc = nil
	file_proto_msa_monitor_proto_goTypes = nil
	file_proto_msa_monitor_proto_depIdxs = nil
}
