// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: proto/msa_observer.proto

package msa_observer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	msa_utils "x-msa-core/grpc/msa_utils"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestPushFirst struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Host string `protobuf:"bytes,1,opt,name=Host,proto3" json:"Host,omitempty"`
	Port int32  `protobuf:"varint,2,opt,name=Port,proto3" json:"Port,omitempty"`
	Key  string `protobuf:"bytes,3,opt,name=Key,proto3" json:"Key,omitempty"`
}

func (x *RequestPushFirst) Reset() {
	*x = RequestPushFirst{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_msa_observer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestPushFirst) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestPushFirst) ProtoMessage() {}

func (x *RequestPushFirst) ProtoReflect() protoreflect.Message {
	mi := &file_proto_msa_observer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestPushFirst.ProtoReflect.Descriptor instead.
func (*RequestPushFirst) Descriptor() ([]byte, []int) {
	return file_proto_msa_observer_proto_rawDescGZIP(), []int{0}
}

func (x *RequestPushFirst) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *RequestPushFirst) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *RequestPushFirst) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type RequestPushStats struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key    string  `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	CurCpu float32 `protobuf:"fixed32,2,opt,name=CurCpu,proto3" json:"CurCpu,omitempty"`
	MaxCpu float32 `protobuf:"fixed32,3,opt,name=MaxCpu,proto3" json:"MaxCpu,omitempty"`
	CurRam float32 `protobuf:"fixed32,4,opt,name=CurRam,proto3" json:"CurRam,omitempty"`
	MaxRam float32 `protobuf:"fixed32,5,opt,name=MaxRam,proto3" json:"MaxRam,omitempty"`
	CurHdd float32 `protobuf:"fixed32,6,opt,name=CurHdd,proto3" json:"CurHdd,omitempty"`
	MaxHdd float32 `protobuf:"fixed32,7,opt,name=MaxHdd,proto3" json:"MaxHdd,omitempty"`
}

func (x *RequestPushStats) Reset() {
	*x = RequestPushStats{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_msa_observer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestPushStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestPushStats) ProtoMessage() {}

func (x *RequestPushStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_msa_observer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestPushStats.ProtoReflect.Descriptor instead.
func (*RequestPushStats) Descriptor() ([]byte, []int) {
	return file_proto_msa_observer_proto_rawDescGZIP(), []int{1}
}

func (x *RequestPushStats) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *RequestPushStats) GetCurCpu() float32 {
	if x != nil {
		return x.CurCpu
	}
	return 0
}

func (x *RequestPushStats) GetMaxCpu() float32 {
	if x != nil {
		return x.MaxCpu
	}
	return 0
}

func (x *RequestPushStats) GetCurRam() float32 {
	if x != nil {
		return x.CurRam
	}
	return 0
}

func (x *RequestPushStats) GetMaxRam() float32 {
	if x != nil {
		return x.MaxRam
	}
	return 0
}

func (x *RequestPushStats) GetCurHdd() float32 {
	if x != nil {
		return x.CurHdd
	}
	return 0
}

func (x *RequestPushStats) GetMaxHdd() float32 {
	if x != nil {
		return x.MaxHdd
	}
	return 0
}

type RequestPushStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key    string                  `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	IsNew  bool                    `protobuf:"varint,2,opt,name=IsNew,proto3" json:"IsNew,omitempty"`
	Status msa_utils.StatusService `protobuf:"varint,3,opt,name=Status,proto3,enum=msa_utils.StatusService" json:"Status,omitempty"`
}

func (x *RequestPushStatus) Reset() {
	*x = RequestPushStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_msa_observer_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestPushStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestPushStatus) ProtoMessage() {}

func (x *RequestPushStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_msa_observer_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestPushStatus.ProtoReflect.Descriptor instead.
func (*RequestPushStatus) Descriptor() ([]byte, []int) {
	return file_proto_msa_observer_proto_rawDescGZIP(), []int{2}
}

func (x *RequestPushStatus) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *RequestPushStatus) GetIsNew() bool {
	if x != nil {
		return x.IsNew
	}
	return false
}

func (x *RequestPushStatus) GetStatus() msa_utils.StatusService {
	if x != nil {
		return x.Status
	}
	return msa_utils.StatusService(0)
}

type RequestWho struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupType string `protobuf:"bytes,1,opt,name=GroupType,proto3" json:"GroupType,omitempty"`
}

func (x *RequestWho) Reset() {
	*x = RequestWho{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_msa_observer_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestWho) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestWho) ProtoMessage() {}

func (x *RequestWho) ProtoReflect() protoreflect.Message {
	mi := &file_proto_msa_observer_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestWho.ProtoReflect.Descriptor instead.
func (*RequestWho) Descriptor() ([]byte, []int) {
	return file_proto_msa_observer_proto_rawDescGZIP(), []int{3}
}

func (x *RequestWho) GetGroupType() string {
	if x != nil {
		return x.GroupType
	}
	return ""
}

type RequestRestartService struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
}

func (x *RequestRestartService) Reset() {
	*x = RequestRestartService{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_msa_observer_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestRestartService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestRestartService) ProtoMessage() {}

func (x *RequestRestartService) ProtoReflect() protoreflect.Message {
	mi := &file_proto_msa_observer_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestRestartService.ProtoReflect.Descriptor instead.
func (*RequestRestartService) Descriptor() ([]byte, []int) {
	return file_proto_msa_observer_proto_rawDescGZIP(), []int{4}
}

func (x *RequestRestartService) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type ResponsePushFirst struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dependents []*Info `protobuf:"bytes,1,rep,name=Dependents,proto3" json:"Dependents,omitempty"`
}

func (x *ResponsePushFirst) Reset() {
	*x = ResponsePushFirst{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_msa_observer_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponsePushFirst) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponsePushFirst) ProtoMessage() {}

func (x *ResponsePushFirst) ProtoReflect() protoreflect.Message {
	mi := &file_proto_msa_observer_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponsePushFirst.ProtoReflect.Descriptor instead.
func (*ResponsePushFirst) Descriptor() ([]byte, []int) {
	return file_proto_msa_observer_proto_rawDescGZIP(), []int{5}
}

func (x *ResponsePushFirst) GetDependents() []*Info {
	if x != nil {
		return x.Dependents
	}
	return nil
}

type ResponseWho struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
}

func (x *ResponseWho) Reset() {
	*x = ResponseWho{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_msa_observer_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseWho) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseWho) ProtoMessage() {}

func (x *ResponseWho) ProtoReflect() protoreflect.Message {
	mi := &file_proto_msa_observer_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseWho.ProtoReflect.Descriptor instead.
func (*ResponseWho) Descriptor() ([]byte, []int) {
	return file_proto_msa_observer_proto_rawDescGZIP(), []int{6}
}

func (x *ResponseWho) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_msa_observer_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_msa_observer_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_proto_msa_observer_proto_rawDescGZIP(), []int{7}
}

func (x *Response) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type Info struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Host      string `protobuf:"bytes,1,opt,name=Host,proto3" json:"Host,omitempty"`
	Port      int32  `protobuf:"varint,2,opt,name=Port,proto3" json:"Port,omitempty"`
	Key       string `protobuf:"bytes,3,opt,name=Key,proto3" json:"Key,omitempty"`
	GroupType string `protobuf:"bytes,4,opt,name=GroupType,proto3" json:"GroupType,omitempty"`
}

func (x *Info) Reset() {
	*x = Info{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_msa_observer_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Info) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Info) ProtoMessage() {}

func (x *Info) ProtoReflect() protoreflect.Message {
	mi := &file_proto_msa_observer_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Info.ProtoReflect.Descriptor instead.
func (*Info) Descriptor() ([]byte, []int) {
	return file_proto_msa_observer_proto_rawDescGZIP(), []int{8}
}

func (x *Info) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Info) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Info) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Info) GetGroupType() string {
	if x != nil {
		return x.GroupType
	}
	return ""
}

var File_proto_msa_observer_proto protoreflect.FileDescriptor

var file_proto_msa_observer_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x73, 0x61, 0x5f, 0x6f, 0x62, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x6d, 0x73, 0x61, 0x5f,
	0x6f, 0x62, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x1a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x6d, 0x73, 0x61, 0x5f, 0x75, 0x74, 0x69, 0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x4c, 0x0a, 0x10, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x75, 0x73, 0x68, 0x46, 0x69,
	0x72, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x48, 0x6f, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x48, 0x6f, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x6f, 0x72, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x4b,
	0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4b, 0x65, 0x79, 0x22, 0xb4, 0x01,
	0x0a, 0x10, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x75, 0x73, 0x68, 0x53, 0x74, 0x61,
	0x74, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x4b, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x43, 0x75, 0x72, 0x43, 0x70, 0x75, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x43, 0x75, 0x72, 0x43, 0x70, 0x75, 0x12, 0x16, 0x0a, 0x06,
	0x4d, 0x61, 0x78, 0x43, 0x70, 0x75, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x4d, 0x61,
	0x78, 0x43, 0x70, 0x75, 0x12, 0x16, 0x0a, 0x06, 0x43, 0x75, 0x72, 0x52, 0x61, 0x6d, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x43, 0x75, 0x72, 0x52, 0x61, 0x6d, 0x12, 0x16, 0x0a, 0x06,
	0x4d, 0x61, 0x78, 0x52, 0x61, 0x6d, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x4d, 0x61,
	0x78, 0x52, 0x61, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x43, 0x75, 0x72, 0x48, 0x64, 0x64, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x43, 0x75, 0x72, 0x48, 0x64, 0x64, 0x12, 0x16, 0x0a, 0x06,
	0x4d, 0x61, 0x78, 0x48, 0x64, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x4d, 0x61,
	0x78, 0x48, 0x64, 0x64, 0x22, 0x6d, 0x0a, 0x11, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50,
	0x75, 0x73, 0x68, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x49,
	0x73, 0x4e, 0x65, 0x77, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x49, 0x73, 0x4e, 0x65,
	0x77, 0x12, 0x30, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x18, 0x2e, 0x6d, 0x73, 0x61, 0x5f, 0x75, 0x74, 0x69, 0x6c, 0x73, 0x2e, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x06, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x22, 0x2a, 0x0a, 0x0a, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x57, 0x68,
	0x6f, 0x12, 0x1c, 0x0a, 0x09, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x54, 0x79, 0x70, 0x65, 0x22,
	0x29, 0x0a, 0x15, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x74, 0x61, 0x72,
	0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4b, 0x65, 0x79, 0x22, 0x47, 0x0a, 0x11, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x75, 0x73, 0x68, 0x46, 0x69, 0x72, 0x73, 0x74, 0x12,
	0x32, 0x0a, 0x0a, 0x44, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6d, 0x73, 0x61, 0x5f, 0x6f, 0x62, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0a, 0x44, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65,
	0x6e, 0x74, 0x73, 0x22, 0x1f, 0x0a, 0x0b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x57,
	0x68, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x4b, 0x65, 0x79, 0x22, 0x24, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x5e, 0x0a, 0x04, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x48, 0x6f, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x48, 0x6f, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x6f, 0x72, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65,
	0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4b, 0x65, 0x79, 0x12, 0x1c, 0x0a, 0x09,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x54, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x54, 0x79, 0x70, 0x65, 0x32, 0xef, 0x02, 0x0a, 0x08, 0x4f,
	0x62, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x4c, 0x0a, 0x09, 0x50, 0x75, 0x73, 0x68, 0x46,
	0x69, 0x72, 0x73, 0x74, 0x12, 0x1e, 0x2e, 0x6d, 0x73, 0x61, 0x5f, 0x6f, 0x62, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x75, 0x73, 0x68, 0x46,
	0x69, 0x72, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x6d, 0x73, 0x61, 0x5f, 0x6f, 0x62, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x75, 0x73, 0x68,
	0x46, 0x69, 0x72, 0x73, 0x74, 0x12, 0x43, 0x0a, 0x09, 0x50, 0x75, 0x73, 0x68, 0x53, 0x74, 0x61,
	0x74, 0x73, 0x12, 0x1e, 0x2e, 0x6d, 0x73, 0x61, 0x5f, 0x6f, 0x62, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x75, 0x73, 0x68, 0x53, 0x74, 0x61,
	0x74, 0x73, 0x1a, 0x16, 0x2e, 0x6d, 0x73, 0x61, 0x5f, 0x6f, 0x62, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x45, 0x0a, 0x0a, 0x50, 0x75,
	0x73, 0x68, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1f, 0x2e, 0x6d, 0x73, 0x61, 0x5f, 0x6f,
	0x62, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50,
	0x75, 0x73, 0x68, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x1a, 0x16, 0x2e, 0x6d, 0x73, 0x61, 0x5f,
	0x6f, 0x62, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x3a, 0x0a, 0x03, 0x57, 0x68, 0x6f, 0x12, 0x18, 0x2e, 0x6d, 0x73, 0x61, 0x5f, 0x6f,
	0x62, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x57,
	0x68, 0x6f, 0x1a, 0x19, 0x2e, 0x6d, 0x73, 0x61, 0x5f, 0x6f, 0x62, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x57, 0x68, 0x6f, 0x12, 0x4d, 0x0a,
	0x0e, 0x52, 0x65, 0x73, 0x74, 0x61, 0x72, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x23, 0x2e, 0x6d, 0x73, 0x61, 0x5f, 0x6f, 0x62, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x74, 0x61, 0x72, 0x74, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x1a, 0x16, 0x2e, 0x6d, 0x73, 0x61, 0x5f, 0x6f, 0x62, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x13, 0x5a, 0x11,
	0x67, 0x72, 0x70, 0x63, 0x2f, 0x6d, 0x73, 0x61, 0x5f, 0x6f, 0x62, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_msa_observer_proto_rawDescOnce sync.Once
	file_proto_msa_observer_proto_rawDescData = file_proto_msa_observer_proto_rawDesc
)

func file_proto_msa_observer_proto_rawDescGZIP() []byte {
	file_proto_msa_observer_proto_rawDescOnce.Do(func() {
		file_proto_msa_observer_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_msa_observer_proto_rawDescData)
	})
	return file_proto_msa_observer_proto_rawDescData
}

var file_proto_msa_observer_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_msa_observer_proto_goTypes = []interface{}{
	(*RequestPushFirst)(nil),      // 0: msa_observer.RequestPushFirst
	(*RequestPushStats)(nil),      // 1: msa_observer.RequestPushStats
	(*RequestPushStatus)(nil),     // 2: msa_observer.RequestPushStatus
	(*RequestWho)(nil),            // 3: msa_observer.RequestWho
	(*RequestRestartService)(nil), // 4: msa_observer.RequestRestartService
	(*ResponsePushFirst)(nil),     // 5: msa_observer.ResponsePushFirst
	(*ResponseWho)(nil),           // 6: msa_observer.ResponseWho
	(*Response)(nil),              // 7: msa_observer.Response
	(*Info)(nil),                  // 8: msa_observer.Info
	(msa_utils.StatusService)(0),  // 9: msa_utils.StatusService
}
var file_proto_msa_observer_proto_depIdxs = []int32{
	9, // 0: msa_observer.RequestPushStatus.Status:type_name -> msa_utils.StatusService
	8, // 1: msa_observer.ResponsePushFirst.Dependents:type_name -> msa_observer.Info
	0, // 2: msa_observer.Observer.PushFirst:input_type -> msa_observer.RequestPushFirst
	1, // 3: msa_observer.Observer.PushStats:input_type -> msa_observer.RequestPushStats
	2, // 4: msa_observer.Observer.PushStatus:input_type -> msa_observer.RequestPushStatus
	3, // 5: msa_observer.Observer.Who:input_type -> msa_observer.RequestWho
	4, // 6: msa_observer.Observer.RestartService:input_type -> msa_observer.RequestRestartService
	5, // 7: msa_observer.Observer.PushFirst:output_type -> msa_observer.ResponsePushFirst
	7, // 8: msa_observer.Observer.PushStats:output_type -> msa_observer.Response
	7, // 9: msa_observer.Observer.PushStatus:output_type -> msa_observer.Response
	6, // 10: msa_observer.Observer.Who:output_type -> msa_observer.ResponseWho
	7, // 11: msa_observer.Observer.RestartService:output_type -> msa_observer.Response
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_msa_observer_proto_init() }
func file_proto_msa_observer_proto_init() {
	if File_proto_msa_observer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_msa_observer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestPushFirst); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_msa_observer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestPushStats); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_msa_observer_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestPushStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_msa_observer_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestWho); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_msa_observer_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestRestartService); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_msa_observer_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponsePushFirst); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_msa_observer_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseWho); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_msa_observer_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_msa_observer_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Info); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_msa_observer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_msa_observer_proto_goTypes,
		DependencyIndexes: file_proto_msa_observer_proto_depIdxs,
		MessageInfos:      file_proto_msa_observer_proto_msgTypes,
	}.Build()
	File_proto_msa_observer_proto = out.File
	file_proto_msa_observer_proto_rawDesc = nil
	file_proto_msa_observer_proto_goTypes = nil
	file_proto_msa_observer_proto_depIdxs = nil
}
