// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: proto/msa_utils.proto

package msa_utils

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RoleService int32

const (
	RoleService_Observer  RoleService = 0
	RoleService_Monitor   RoleService = 1
	RoleService_Support   RoleService = 2
	RoleService_Interface RoleService = 3
)

// Enum value maps for RoleService.
var (
	RoleService_name = map[int32]string{
		0: "Observer",
		1: "Monitor",
		2: "Support",
		3: "Interface",
	}
	RoleService_value = map[string]int32{
		"Observer":  0,
		"Monitor":   1,
		"Support":   2,
		"Interface": 3,
	}
)

func (x RoleService) Enum() *RoleService {
	p := new(RoleService)
	*p = x
	return p
}

func (x RoleService) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoleService) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_msa_utils_proto_enumTypes[0].Descriptor()
}

func (RoleService) Type() protoreflect.EnumType {
	return &file_proto_msa_utils_proto_enumTypes[0]
}

func (x RoleService) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoleService.Descriptor instead.
func (RoleService) EnumDescriptor() ([]byte, []int) {
	return file_proto_msa_utils_proto_rawDescGZIP(), []int{0}
}

type StatusService int32

const (
	StatusService_On       StatusService = 0
	StatusService_Off      StatusService = 1
	StatusService_Starts   StatusService = 2
	StatusService_Stops    StatusService = 3
	StatusService_Restarts StatusService = 4
	StatusService_Down     StatusService = 5
	StatusService_Created  StatusService = 6
	StatusService_Updated  StatusService = 7
	StatusService_Deleted  StatusService = 8
)

// Enum value maps for StatusService.
var (
	StatusService_name = map[int32]string{
		0: "On",
		1: "Off",
		2: "Starts",
		3: "Stops",
		4: "Restarts",
		5: "Down",
		6: "Created",
		7: "Updated",
		8: "Deleted",
	}
	StatusService_value = map[string]int32{
		"On":       0,
		"Off":      1,
		"Starts":   2,
		"Stops":    3,
		"Restarts": 4,
		"Down":     5,
		"Created":  6,
		"Updated":  7,
		"Deleted":  8,
	}
)

func (x StatusService) Enum() *StatusService {
	p := new(StatusService)
	*p = x
	return p
}

func (x StatusService) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusService) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_msa_utils_proto_enumTypes[1].Descriptor()
}

func (StatusService) Type() protoreflect.EnumType {
	return &file_proto_msa_utils_proto_enumTypes[1]
}

func (x StatusService) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatusService.Descriptor instead.
func (StatusService) EnumDescriptor() ([]byte, []int) {
	return file_proto_msa_utils_proto_rawDescGZIP(), []int{1}
}

type Commands int32

const (
	Commands_Start   Commands = 0
	Commands_Stop    Commands = 1
	Commands_Restart Commands = 2
)

// Enum value maps for Commands.
var (
	Commands_name = map[int32]string{
		0: "Start",
		1: "Stop",
		2: "Restart",
	}
	Commands_value = map[string]int32{
		"Start":   0,
		"Stop":    1,
		"Restart": 2,
	}
)

func (x Commands) Enum() *Commands {
	p := new(Commands)
	*p = x
	return p
}

func (x Commands) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Commands) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_msa_utils_proto_enumTypes[2].Descriptor()
}

func (Commands) Type() protoreflect.EnumType {
	return &file_proto_msa_utils_proto_enumTypes[2]
}

func (x Commands) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Commands.Descriptor instead.
func (Commands) EnumDescriptor() ([]byte, []int) {
	return file_proto_msa_utils_proto_rawDescGZIP(), []int{2}
}

var File_proto_msa_utils_proto protoreflect.FileDescriptor

var file_proto_msa_utils_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x73, 0x61, 0x5f, 0x75, 0x74, 0x69, 0x6c,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x6d, 0x73, 0x61, 0x5f, 0x75, 0x74, 0x69,
	0x6c, 0x73, 0x2a, 0x44, 0x0a, 0x0b, 0x52, 0x6f, 0x6c, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x0c, 0x0a, 0x08, 0x4f, 0x62, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x10, 0x00, 0x12,
	0x0b, 0x0a, 0x07, 0x4d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07,
	0x53, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09, 0x49, 0x6e, 0x74,
	0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x10, 0x03, 0x2a, 0x76, 0x0a, 0x0d, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x6e, 0x10,
	0x00, 0x12, 0x07, 0x0a, 0x03, 0x4f, 0x66, 0x66, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x73, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x53, 0x74, 0x6f, 0x70, 0x73, 0x10,
	0x03, 0x12, 0x0c, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x74, 0x61, 0x72, 0x74, 0x73, 0x10, 0x04, 0x12,
	0x08, 0x0a, 0x04, 0x44, 0x6f, 0x77, 0x6e, 0x10, 0x05, 0x12, 0x0b, 0x0a, 0x07, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x10, 0x06, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x64, 0x10, 0x07, 0x12, 0x0b, 0x0a, 0x07, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x10, 0x08,
	0x2a, 0x2c, 0x0a, 0x08, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x12, 0x09, 0x0a, 0x05,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x53, 0x74, 0x6f, 0x70, 0x10,
	0x01, 0x12, 0x0b, 0x0a, 0x07, 0x52, 0x65, 0x73, 0x74, 0x61, 0x72, 0x74, 0x10, 0x02, 0x42, 0x10,
	0x5a, 0x0e, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x6d, 0x73, 0x61, 0x5f, 0x75, 0x74, 0x69, 0x6c, 0x73,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_msa_utils_proto_rawDescOnce sync.Once
	file_proto_msa_utils_proto_rawDescData = file_proto_msa_utils_proto_rawDesc
)

func file_proto_msa_utils_proto_rawDescGZIP() []byte {
	file_proto_msa_utils_proto_rawDescOnce.Do(func() {
		file_proto_msa_utils_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_msa_utils_proto_rawDescData)
	})
	return file_proto_msa_utils_proto_rawDescData
}

var file_proto_msa_utils_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_msa_utils_proto_goTypes = []interface{}{
	(RoleService)(0),   // 0: msa_utils.RoleService
	(StatusService)(0), // 1: msa_utils.StatusService
	(Commands)(0),      // 2: msa_utils.Commands
}
var file_proto_msa_utils_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_msa_utils_proto_init() }
func file_proto_msa_utils_proto_init() {
	if File_proto_msa_utils_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_msa_utils_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_msa_utils_proto_goTypes,
		DependencyIndexes: file_proto_msa_utils_proto_depIdxs,
		EnumInfos:         file_proto_msa_utils_proto_enumTypes,
	}.Build()
	File_proto_msa_utils_proto = out.File
	file_proto_msa_utils_proto_rawDesc = nil
	file_proto_msa_utils_proto_goTypes = nil
	file_proto_msa_utils_proto_depIdxs = nil
}
